theme: jekyll-theme-minimal
title: Projeto Tokyo-Data
logo: asset/pv.jfif
description: Análise do Plenário Virtual na Pandemia
show_downloads: true
link_material: "https://www.dropbox.com/s/tpca99zhcnttu72/20200305_WBS-Projeto%20transparencia.pdf?dl=0"
